# Generated by Django 4.2.3 on 2023-08-05 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CRM', '0002_remove_customer_summary'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='summary',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
